[package]
name = "wptcoverage"
version = "0.1.0"
authors = ["James Graham <james@hoppipolla.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.9"
serde = "1"
serde_json = "1"
structopt = "0.2"